databases:
  - name: ODEKAKE_DB
    databaseName: odekake_db
    user: ODEKAKE
    region: singapore

services:
  - type: web
    name: ODEKAKE
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ODEKAKE_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
